spring:
  application.name: gigastore
  datasource:
    url: jdbc:postgresql://localhost:5432/gigastore
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
order-confirmation:
  host: https://email-api.example.com